{% set name = "markdown2" %}
{% set version = "2.5.3" %}
{% set sha256 = "4d502953a4633408b0ab3ec503c5d6984d1b14307e32b325ec7d16ea57524895" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - markdown2 = markdown2:main
  skip: true  # [py<39,<40]

requirements:
  host:
    - pip
    - python
  run:
    - python
  run_constrained:
    - pygments >=2.7.3

test:
  imports:
    - markdown2
  commands:
    - markdown2 --help

about:
  home: https://github.com/trentm/python-markdown2
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: fast and complete Python implementation of Markdown
  description: |
    Markdown is a text-to-HTML filter; it translates an easy-to-read / easy-to-write structured
    text format into HTML.
  doc_url: https://pypi.org/pypi/markdown2
  doc_source_url: https://github.com/trentm/python-markdown2/blob/master/README.md
  dev_url: https://github.com/waylan/Python-Markdown

extra:
  recipe-maintainers:
    - jakirkham
    - pelson