{% set name = "markdown2" %}
{% set version = "2.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 001547e68f6e7fcf0f1cb83f7e82f48aa7d48b2c6a321f0cd20a853a8a2d1664

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - markdown2 = markdown2:main
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
  run_constrained:
    # code_syntax_highlighting
    - pygments >=2.7.3

test:
  source_files:
    - test
  imports:
    - markdown2
  requires:
    - pip
    # Tests are not working with pytest 8
    # 'yield' keyword is allowed in fixtures, but not in tests (test_cases)
    - pytest <8
  commands:
    - pip check
    - markdown2 --help
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v test

about:
  home: https://github.com/trentm/python-markdown2
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: fast and complete Python implementation of Markdown
  description: |
    Markdown is a text-to-HTML filter; it translates an easy-to-read / easy-to-write structured
    text format into HTML.
  doc_url: https://github.com/trentm/python-markdown2/blob/master/README.md
  dev_url: https://github.com/trentm/python-markdown2

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
