travis:
  secure:
    BINSTAR_TOKEN: YL+OsY2BIEHyLpdLQoxiIWCrxTb7OAnPdTMcawJfJy/9JL/9RCBg7b3/sXSF/iMZjW/7bxyshPjkaY2CeBXVQZCSfASvpQvSOt1gHW04OlxVwTohn36lJuwYW03gc+jqFt13MiWaopZuQiRc46W4et1UGdCkNv1q2jqBTpzS1XrgRkDGdgTkBNPrnMbmwaGcu1884oD4NCmq+EvgS4fgbKquUu833caSXFlI6kiT0Ji7e5jf9ZpAzpaSiyXKAztYRSXYXvU9iGETzh4kqC4hkad7FJQ5FV98jim478iHpDaGqfkbV0SXiCbsSTyxM59L4dp5zCzO44If4kUIgVfjOlbVuidZ6L9TxOv1PHi5e7ZdqOVwODfpnf+H6qhtke8gMmYSwZvYl0So5JNhG8wHMBx1AOmuMHZPAMKztdhkoyqlNpwQgSnxwpQZtjzRMnCBukXQtpquiCujcXQzvAost+VZFEi4j8QigucHXV7DyE5wSiMkWEXCIagVJmdwlgtUtEo1XodUWprbJqPWsCrOQR+XDd3kUvdmn5oFjr6Xepif9TclERW1jVdRfVfA2lOLKd4QJGPv54/07aMK9wrODxVi1fobmE8ktavxhsHTzYdqDCEuVvN+xLZabsvOaxSX7t09bbC6f2E30VoEEp10RdEXPGqdy6tUx2S/cwd440c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
