travis:
  secure:
    BINSTAR_TOKEN: nqwn/XkgKEaAcDeL00LLTq2tf5Or9oDhbfD5BwVCqjzKOVq5aKmSJvZhZZ/2AIOINKSCq3nUD11r3JanBTF0YfejEb94Glwyr5krE0PpXL9zQ/OsCIJplSmWngL81AOx7ouDPbBOYGR2CMFvbhIuhQc9k2B/BZyaGtpyJ1DeYLCABqQpXaz0Qr7Me8VRfXyo1sKq/f3CkJOAaY7mvJEQI02qmPCoGcCQ123Sx9gEF7k29N2fVrih/1/Gb741XvE59uOkQVTADAumw2Z5dq8qIbZFONp4EkXO0LSoJi8kPsg1UMTRM279S56Gu8zQhBmBeP0u70JJTIYtseMHOsbHShsQhMURV4sH/6ALJjKtPY9LBggwMCusel4R95y/8XBib2nat36fRRrTE/QGOohIy5TwR22UWTsc82n6rP4QBbuSDde6yzfvl8c5J+6/PK0sfnJUEv83HnuZmLaYCdlf5kVkT0eGkOkZw3XjyxEyV5KN5uCy+F5SpB1E9Oa6aZhWSirsDsaNb/bRn//rA0bslA14BEpKJFRQTLGLWQkgVIEwuw8MbiesOggfTrDGichPJOPrW7rrD/2CAY9+HHISJ+bPREoS/6BmwgX1OznRGGBmCM8S+suOnQOIgrpsfdUgv2VR0zflytLg6Zv4LLflJQLj23gYUJgIe1+QRRB5OvY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
