travis:
  secure:
    BINSTAR_TOKEN: ehatlVA/Y1OvQz/X7IpOdEWkMAWXjDReRBuZF7L+fgbgf8IDTLB4zrdVocdUmWVTl49XOdwVBLae0Qp77uEvjRjM1qnBqMoYAINmsRaymxcD1++dDTAqj+LHYnTXLKJu42FaewZLepfRc82Uaa9j8Gx/iogcDAWWUDa7qyIlowvuWIItdoKqWtfgF6BQ6Jy3eQq3xNpvDTbtR/C8FcwKQ2I6MJj79wl3p9IJ2PV4k638xlH1SUEgU7KyHX1v+X+6uLso/GZw44EIkNswDOQVACO8Q7yhTP9tAueZT3qnxwQsQbLz+OOZhFBywxlOHxkv44BEzCaAoUolxhLzQmtPP2ghN4F/kHynKUXx1zqSxzWLnbeo8VVA7gMPUYSeu8qnR+pbHOzFkD3esYw93HKjLDf9S35Us1ruru6tO83SytXojs0k3YtZc0DIvurjNuIR9JrVkvlUYA1XvAHP9IZyhw7qiIHPgtpJTqZdZTJzEH1G9XMEUEU1NyBinuiJFJeeRnR/Bm2tRS09esSF9c/ASkkiCH/Q9qptN3wen84ZhxQlnrrJwUsiJ5sFCov1UhDP/tdpyDPmlOgl94BwX9UXeScjuLJ7hA/ZTxN43KK9TUkTzC8sbDciPFPKQe9bbMBhggAVntK/93O5nQvgZnXJZJnt2Z+PBCoAPgPiHAhQE4k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
